name: ci

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  ci:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [14]

    env:
      TZ: Asia/Tokyo

    steps:
      - name: Checkout 🛎
        uses: actions/checkout@master

      - name: Setup node env 🏗
        uses: actions/setup-node@v2.2.0
        with:
          node-version: ${{ matrix.node }}
          cache: 'yarn'

      - name: Install dependencies 👨🏻‍💻
        if: steps.yarn-cache.outputs.cache-hit != 'true'
        run: yarn install --frozen-lockfile

      - name: Run eslint 👀
        uses: reviewdog/action-eslint@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-pr-review
          eslint_flags: '. --ext .js,.ts,.vue --ignore-path .gitignore'
          level: error

      - name: Prepare build
        run: echo "{ \"consumer_key\":\"\", \"consumer_secret\":\"\"}" > apikey-release.json

      - name: Build
        run: yarn build
